import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';
import ScrollProvider from './ScrollProvider';

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Supereme Group',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // suppressHydrationWarning prevents React from logging hydration attribute/DOM mismatch
    // warnings for this subtree (useful when browser extensions inject attributes like
    // `fusion-extension-loaded` or `webcrx` that differ from the server HTML).
    <html lang='en' suppressHydrationWarning>
      <body className={`${manrope.variable} antialiased`}>
        <ScrollProvider />
        {children}
      </body>
    </html>
  );
}
